name: Build Minescript (Fabric)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout Minescript
        uses: actions/checkout@v4
    
      # 2. Hapus Forge & NeoForge (BIAR GAK KE-LOAD)
      - name: Remove Forge temporarily
        run: |
          sed -i '/forge/d' settings.gradle
          sed -i '/neoforge/d' settings.gradle
    
      # 3. Setup Java
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
    
      # 4. (opsional) force gradle 8
      - name: Force Gradle 8 Wrapper
        run: |
          sed -i 's/gradle-9.*/gradle-8.7-bin.zip/g' gradle/wrapper/gradle-wrapper.properties
    
      # 5. Clone Pyjinn
      - name: Clone Pyjinn
        run: git clone https://github.com/maxuser0/pyjinn.git
    
      # 6. Build Pyjinn
      - name: Build & Publish Pyjinn
        working-directory: pyjinn
        run: |
          chmod +x gradlew
          ./gradlew interpreter:publishToMavenLocal
    
      # 7. Build Fabric
      - name: Build Fabric Mod
        run: ./gradlew :fabric:build
        with:
          name: minescript-fabric
          path: fabric/build/libs/*.jar
